# Generated by Django 5.2 on 2025-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_template', models.CharField(choices=[('base.html', 'Standard'), ('base_dark.html', 'Dark Mode')], default='base.html', max_length=255, verbose_name='Basis-Template')),
            ],
            options={
                'verbose_name_plural': 'Website-Einstellungen',
            },
        ),
    ]
