# Generated by Django 5.2 on 2025-05-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='base_template',
            field=models.CharField(choices=[('base.html', 'Standard'), ('base_dark.html', 'Dark Mode')], default='base.html', max_length=255, verbose_name='Auswahl des base.html'),
        ),
    ]
