# Generated by Django 5.2 on 2025-05-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0002_alter_sitesettings_base_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Menü Titel')),
                ('slug', models.SlugField(blank=True, help_text='Wird für die URL und die Section-ID verwendet (automatisch generiert, kann angepasst werden)', unique=True)),
                ('order', models.IntegerField(default=0, help_text='Bestimmt die Reihenfolge im Menü', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Menüeintrag',
                'verbose_name_plural': 'Menüeinträge',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='base_template',
            field=models.CharField(choices=[('base.html', 'Standard'), ('base_dark.html', 'Dark Mode')], default='base.html', max_length=255, verbose_name='Auswahl des Basis Templates'),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website_settings.menuitem', verbose_name='Menüeintrag')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Section Überschrift')),
                ('content', models.TextField(blank=True, verbose_name='Section Inhalt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Section Bild')),
                ('order', models.IntegerField(default=0, help_text='Bestimmt die Reihenfolge der Sections auf der Seite', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order'],
            },
        ),
    ]
