# Generated by Django 5.2 on 2025-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0003_menuitem_alter_sitesettings_base_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_theme_switcher',
            field=models.BooleanField(default=True, verbose_name='Theme-Umschalter anzeigen'),
        ),
    ]
