# Generated by Django 5.2 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0004_sitesettings_show_theme_switcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo (Schriftzug)'),
        ),
    ]
