# Generated by Django 5.2 on 2025-05-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0006_sitesettings_logo_max_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_max_height',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_vertical_shift',
        ),
    ]
