# Generated by Django 5.2 on 2025-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0007_remove_sitesettings_logo_max_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='base_template',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_max_height',
            field=models.IntegerField(default=80, help_text='Die maximale Höhe des Logos in Pixel.', verbose_name='Maximale Logo-Höhe (Pixel)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_vertical_shift',
            field=models.IntegerField(default=0, help_text='Positiver Wert verschiebt das Logo nach unten, negativer nach oben.', verbose_name='Vertikaler Logo-Versatz (Pixel)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_css',
            field=models.CharField(choices=[('base.css', 'Standard'), ('base_dark.css', 'Dark Mode')], default='base.css', max_length=255, verbose_name='Auswahl des Website-Themes (CSS)'),
        ),
    ]
