# Generated by Django 5.2 on 2025-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0008_remove_sitesettings_base_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='theme_css',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('light', 'Helles Design'), ('dark', 'Dunkles Design')], default='light', max_length=10, verbose_name='Aktives Website-Design'),
        ),
    ]
