# Generated by Django 5.2 on 2025-05-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0009_remove_sitesettings_theme_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_theme_switcher',
        ),
    ]
