# Generated by Django 5.2 on 2025-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0010_remove_sitesettings_show_theme_switcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_horizontal_shift',
            field=models.IntegerField(default=0, help_text='Positiver Wert verschiebt das Logo nach rechts, negativer nach links.', verbose_name='Horizontaler Logo-Versatz (Pixel)'),
        ),
    ]
