# Generated by Django 5.2 on 2025-05-09 19:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0011_sitesettings_logo_horizontal_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_color',
            field=colorfield.fields.ColorField(default='#343a40', image_field=None, max_length=25, samples=None, verbose_name='Menu-Hintergrundfarbe'),
        ),
    ]
