# Generated by Django 5.2 on 2025-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0015_pagesection_author_pagesection_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='layout',
            field=models.CharField(choices=[('one-column', 'Einspaltig'), ('two-columns-left', 'Zweispaltig (Bild links)'), ('two-columns-right', 'Zweispaltig (Bild rechts)')], default='one-column', max_length=20, verbose_name='Layout'),
        ),
    ]
