# Generated by Django 5.2 on 2025-05-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0016_pagesection_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='background_color',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('bg-light', 'Hell'), ('bg-dark', 'Dunkel'), ('bg-white', 'Weiß'), ('bg-primary', 'Primär'), ('bg-secondary', 'Sekundär')], max_length=20, verbose_name='Hintergrundfarbe'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='border',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('border', 'Einfach'), ('border-top', 'Oben'), ('border-bottom', 'Unten'), ('border-left', 'Links'), ('border-right', 'Rechts'), ('border-primary', 'Primär'), ('border-secondary', 'Sekundär')], max_length=20, verbose_name='Umrandung'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='font_italic',
            field=models.BooleanField(default=False, verbose_name='Kursiv'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='font_weight',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('fw-bold', 'Fett'), ('fw-light', 'Dünn')], max_length=10, verbose_name='Schriftstärke'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='margin',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('m-1', 'Klein (1)'), ('m-2', 'Mittel (2)'), ('mb-3', 'Unten Groß (mb-3)')], max_length=10, verbose_name='Margin'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='padding',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('p-1', 'Klein (1)'), ('p-2', 'Mittel (2)'), ('p-3', 'Groß (3)'), ('py-2', 'Vertikal Mittel (py-2)'), ('px-3', 'Horizontal Groß (px-3)')], max_length=10, verbose_name='Padding'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='rounded',
            field=models.BooleanField(default=False, verbose_name='Abgerundete Ecken'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='shadow',
            field=models.BooleanField(default=False, verbose_name='Schatten'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='text_align',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('text-start', 'Links'), ('text-center', 'Zentriert'), ('text-end', 'Rechts')], max_length=11, verbose_name='Textausrichtung'),
        ),
    ]
