# Generated by Django 5.2 on 2025-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0018_alter_pagesection_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='background_color',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('bg-light', 'Hell'), ('bg-dark', 'Dunkel'), ('bg-white', 'Weiß'), ('bg-primary', 'Primär'), ('bg-secondary', 'Sekundär')], default='#ffffff', max_length=20, verbose_name='Hintergrundfarbe'),
        ),
    ]
