# Generated by Django 5.2 on 2025-05-13 20:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0019_alter_pagesection_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='section_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Textfarbe der Section'),
        ),
    ]
