# Generated by Django 5.2 on 2025-05-13 20:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0020_pagesection_section_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Hintergrundfarbe'),
        ),
    ]
