# Generated by Django 5.2 on 2025-05-14 15:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0021_alter_pagesection_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='first_paragraph',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Erster Absatz (Fett)'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Section Inhalt'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='layout',
            field=models.CharField(choices=[('one-column', 'Einspaltig'), ('two-columns-left', 'Zweispaltig (Bild links)'), ('two-columns-right', 'Zweispaltig (Bild rechts)'), ('paper-article', 'Paper Artikel')], default='one-column', max_length=20, verbose_name='Layout'),
        ),
    ]
