# Generated by Django 5.2 on 2025-05-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_settings', '0022_pagesection_first_paragraph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='first_paragraph',
        ),
    ]
